In [1]:
!pip install pandas scikit-learn

Requirement already satisfied: pandas in c:\users\raurk\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\raurk\anaconda3\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\raurk\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\raurk\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\raurk\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\raurk\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\raurk\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\raurk\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\raurk\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\raurk\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
jobs = [

    {
        "Role":"Machine Learning Intern",

        "Description":
        """
        Python
        Machine Learning
        Deep Learning
        TensorFlow
        Pandas
        NumPy
        Scikit-Learn
        """
    },

    {
        "Role":"Data Analyst",

        "Description":
        """
        SQL
        Excel
        Power BI
        Python
        Pandas
        Data Analysis
        """
    },

    {
        "Role":"Software Engineer",

        "Description":
        """
        Java
        C++
        Data Structures
        Algorithms
        Git
        """
    },

    {
        "Role":"AI Engineer",

        "Description":
        """
        Python
        Deep Learning
        TensorFlow
        PyTorch
        NLP
        Computer Vision
        """
    },

    {
        "Role":"Data Scientist",

        "Description":
        """
        Python
        SQL
        Machine Learning
        Statistics
        Pandas
        NumPy
        """
    }
]

In [4]:
jobs_df = pd.DataFrame(jobs)

jobs_df

                      Role                                        Description
0  Machine Learning Intern  \n        Python\n        Machine Learning\n  ...
1             Data Analyst  \n        SQL\n        Excel\n        Power BI...
2        Software Engineer  \n        Java\n        C++\n        Data Stru...
3              AI Engineer  \n        Python\n        Deep Learning\n     ...
4           Data Scientist  \n        Python\n        SQL\n        Machine...

In [5]:
resume_skills = [

    "python",
    "machine learning",
    "numpy",
    "pandas",
    "git"
]

In [6]:
resume_profile = " ".join(resume_skills)

print(resume_profile)

python machine learning numpy pandas git

In [7]:
corpus = [resume_profile]

corpus.extend(
    jobs_df["Description"].tolist()
)

len(corpus)

6

In [8]:
vectorizer = TfidfVectorizer()

vectors = vectorizer.fit_transform(
    corpus
)

In [11]:
resume_vector = vectors[0]

job_vectors = vectors[1:]

similarities = cosine_similarity(
    resume_vector,
    job_vectors
)

In [12]:
jobs_df["Match Score"] = similarities[0] * 100

jobs_df

,Role,Description,Match Score
0,Machine Learning Intern,\n Python\n Machine Learning\n ...,56.172966
1,Data Analyst,\n SQL\n Excel\n Power BI...,15.617408
2,Software Engineer,\n Java\n C++\n Data Stru...,20.016380
3,AI Engineer,\n Python\n Deep Learning\n ...,15.617408
4,Data Scientist,\n Python\n SQL\n Machine...,62.974149

In [13]:
recommended_jobs = jobs_df.sort_values(
    by="Match Score",
    ascending=False
)

recommended_jobs

,Role,Description,Match Score
4,Data Scientist,\n Python\n SQL\n Machine...,62.974149
0,Machine Learning Intern,\n Python\n Machine Learning\n ...,56.172966
2,Software Engineer,\n Java\n C++\n Data Stru...,20.016380
1,Data Analyst,\n SQL\n Excel\n Power BI...,15.617408
3,AI Engineer,\n Python\n Deep Learning\n ...,15.617408

In [14]:
top_jobs = recommended_jobs.head(5)

top_jobs

,Role,Description,Match Score
4,Data Scientist,\n Python\n SQL\n Machine...,62.974149
0,Machine Learning Intern,\n Python\n Machine Learning\n ...,56.172966
2,Software Engineer,\n Java\n C++\n Data Stru...,20.016380
1,Data Analyst,\n SQL\n Excel\n Power BI...,15.617408
3,AI Engineer,\n Python\n Deep Learning\n ...,15.617408

In [15]:
for i,row in top_jobs.iterrows():

    print("="*50)

    print("Role:", row["Role"])

    print(
        "Match Score:",
        round(
            row["Match Score"],
            2
        ),
        "%"
    )

    print("="*50)

==================================================
Role: Data Scientist
Match Score: 62.97 %
==================================================
==================================================
Role: Machine Learning Intern
Match Score: 56.17 %
==================================================
==================================================
Role: Software Engineer
Match Score: 20.02 %
==================================================
==================================================
Role: Data Analyst
Match Score: 15.62 %
==================================================
==================================================
Role: AI Engineer
Match Score: 15.62 %
==================================================

In [16]:
def recommendation_label(score):

    if score >= 80:
        return "Highly Recommended"

    elif score >= 60:
        return "Recommended"

    elif score >= 40:
        return "Consider Learning"

    else:
        return "Low Match"

In [17]:
jobs_df["Recommendation"] = jobs_df[
    "Match Score"
].apply(
    recommendation_label
)

jobs_df

,Role,Description,Match Score,Recommendation
0,Machine Learning Intern,\n Python\n Machine Learning\n ...,56.172966,Consider Learning
1,Data Analyst,\n SQL\n Excel\n Power BI...,15.617408,Low Match
2,Software Engineer,\n Java\n C++\n Data Stru...,20.016380,Low Match
3,AI Engineer,\n Python\n Deep Learning\n ...,15.617408,Low Match
4,Data Scientist,\n Python\n SQL\n Machine...,62.974149,Recommended

In [18]:
jobs_df.to_csv(
    "../outputs/job_recommendations.csv",
    index=False
)

print(
    "Recommendations Saved"
)

Recommendations Saved

In [19]:
best_job = jobs_df.sort_values(
    by="Match Score",
    ascending=False
).iloc[0]

print(
    "Best Career Match:"
)

print(
    best_job["Role"]
)

print(
    round(
        best_job["Match Score"],
        2
    ),
    "%"
)

Best Career Match:
Data Scientist
62.97 %

In [20]:
def missing_skills_for_job(
    job_description,
    resume_skills
):

    job_skills = job_description.lower().split()

    missing = []

    for skill in job_skills:

        if skill not in resume_skills:

            missing.append(skill)

    return list(set(missing))

In [21]:
jobs_df["Missing Skills"] = jobs_df[
    "Description"
].apply(

    lambda x:
    missing_skills_for_job(
        x,
        resume_skills
    )
)

jobs_df[
    [
        "Role",
        "Missing Skills"
    ]
]

                      Role                                     Missing Skills
0  Machine Learning Intern  [tensorflow, scikit-learn, learning, machine, ...
1             Data Analyst            [data, bi, analysis, excel, power, sql]
2        Software Engineer          [java, data, structures, c++, algorithms]
3              AI Engineer  [nlp, tensorflow, vision, pytorch, learning, c...
4           Data Scientist               [sql, learning, machine, statistics]